name: Swift Package Tests

on:
  push:
    branches: [ develop ]
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'
      - '.github/workflows/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'
      - '.github/workflows/**'

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: fwal/setup-swift@v2
      with:
        swift-version: "5.9"

    - name: Build Package
      run: swift build --build-tests

    - name: Run Unit Tests
      run: swift test