name: Swift Package Tests

on:
  push:
    branches: [ develop ]
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'
      - '.github/workflows/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  self-hosted-build:
    name: Self-hosted Build and Test
    runs-on: [self-hosted, macbook-pro-m1]
    steps:
      - uses: ./github/actions/build-test-action

  github-hosted-build:
    name: Github-hosted Fallback Build and Test
    needs: self-hosted-build
    if: failure()
    runs-on: macos-latest
    steps:
      - uses: ./github/actions/build-test-action